package upbit

var DESCRIPTION = map[string]string{
	// account
	"account":                        "자산",
	"account.Account":                "계좌 정보",
	"account.Account.Currency":       "화폐를 의미하는 영문 대문자 코드",
	"account.Account.Balance":        "주문가능 금액/수량",
	"account.Account.Locked":         "주문 중 묶여있는 금액/수량",
	"account.Account.AvgKrwBuyPrice": "매수평균가",
	"account.Account.Modified":       "매수평균가 수정 여부",
	// order
	"order":                             "주문",
	"order.Chance":                      "주문 가능 정보",
	"order.Chance.BidFee":               "매수 수수료 비율",
	"order.Chance.AskFee":               "매도 수수료 비율",
	"order.Chance.Market":               "마켓에 대한 정보",
	"order.Chance.Market.ID":            "마켓의 유일 키",
	"order.Chance.Market.Name":          "마켓 이름",
	"order.Chance.Market.OrderTypes":    "지원 주문 방식",
	"order.Chance.Market.OrderSide":     "지원 주문 종류",
	"order.Chance.Market.Bid":           "매수시 제약사항",
	"order.Chance.Market.Bid.Currency":  "화폐를 의미하는 영문 대문자 코드",
	"order.Chance.Market.Bid.PriceUnit": "주문금액 단위",
	"order.Chance.Market.Bid.MinTotal":  "최소 매도/매수 금액",
	"order.Chance.Market.Ask":           "매도시 제약사항",
	"order.Chance.Market.Ask.Currency":  "화폐를 의미하는 영문 대문자 코드",
	"order.Chance.Market.Ask.PriceUnit": "주문금액 단위",
	"order.Chance.Market.Ask.MinTotal":  "최소 매도/매수 금액",
	"order.Chance.Market.MaxTotal":      "최대 매도/매수 금액",
	"order.Chance.Market.State":         "마켓 운영 상태",
	"order.Chance.BidAccount":           "매수 시 사용하는 화폐의 계좌 상태",
	"order.Chance.AskAccount":           "매도 시 사용하는 화폐의 계좌 상태",
	"order.Order":                       "주문 정보",
	"order.Order.UUID":                  "주문의 고유 아이디",
	"order.Order.Side":                  "주문 종류",
	"order.Order.OrdType":               "주문 방식",
	"order.Order.Price":                 "주문 당시 화폐 가격",
	"order.Order.AvgPrice":              "체결 가격의 평균가",
	"order.Order.State":                 "주문 상태",
	"order.Order.Market":                "마켓의 유일키",
	"order.Order.CreatedAt":             "주문 생성 시간",
	"order.Order.Volume":                "사용자가 입력한 주문 양",
	"order.Order.RemainingVolume":       "체결 후 남은 주문 양",
	"order.Order.ReservedFee":           "수수료로 예약된 비용",
	"order.Order.RemainingFee":          "남은 수수료",
	"order.Order.PaidFee":               "사용된 수수료",
	"order.Order.Locked":                "거래에 사용중인 비용",
	"order.Order.ExecutedVolume":        "체결된 양",
	"order.Order.TradeCount":            "해당 주문에 걸린 체결 수",
	"order.Order.Trades":                "체결",
	"order.Order.Trades.Market":         "마켓의 유일 키",
	"order.Order.Trades.UUID":           "체결의 고유 아이디",
	"order.Order.Trades.Price":          "체결 가격",
	"order.Order.Trades.Volume":         "체결 양",
	"order.Order.Trades.Funds":          "체결된 총 가격",
	"order.Order.Trades.Side":           "체결 종류",
	// deposit
	"deposit":                              "입금",
	"deposit.CoinAddress":                  "입금 주소 정보",
	"deposit.CoinAddress.Currency":         "화폐를 의미하는 영문 대문자 코드",
	"deposit.CoinAddress.DepositAddress":   "입금 주소",
	"deposit.CoinAddress.SecondaryAddress": "2차 입금 주소",
	"deposit.Deposit":                      "입금 정보",
	"deposit.Deposit.Type":                 "입출금 종류",
	"deposit.Deposit.UUID":                 "입금에 대한 고유 아이디",
	"deposit.Deposit.Currency":             "화폐를 의미하는 영문 대문자 코드",
	"deposit.Deposit.TxID":                 "입금의 트랜젝션 아이디",
	"deposit.Deposit.State":                "입금 상태",
	"deposit.Deposit.CreatedAt":            "입금 생성 시간",
	"deposit.Deposit.DoneAt":               "입금 완료 시간",
	"deposit.Deposit.Amount":               "입금 수량",
	"deposit.Deposit.Fee":                  "입금 수수료",
	"deposit.Deposit.TransactionType":      "입금 유형",
	// withdraw
	"withdraw":                    "출금",
	"withdraw.Chance":             "출금 가능 정보",
	"withdraw.Chance.MemberLevel": "사용자의 보안등급 정보",
	"withdraw.Chance.MemberLevel.SecurityLevel":        "사용자의 보안등급",
	"withdraw.Chance.MemberLevel.FeeLevel":             "사용자의 수수료등급",
	"withdraw.Chance.MemberLevel.EmailVerified":        "사용자의 이메일 인증 여부",
	"withdraw.Chance.MemberLevel.IdentityAuthVerified": "사용자의 실명 인증 여부",
	"withdraw.Chance.MemberLevel.BankAccountVerified":  "사용자의 계좌 인증 여부",
	"withdraw.Chance.MemberLevel.KakaoPayAuthVerified": "사용자의 카카오페이 인증 여부",
	"withdraw.Chance.MemberLevel.Locked":               "사용자의 계정 보호 상태",
	"withdraw.Chance.MemberLevel.WalletLocked":         "사용자의 출금 보호 상태",
	"withdraw.Chance.Currency":                         "화폐 정보",
	"withdraw.Chance.Currency.Code":                    "화폐를 의미하는 영문 대문자 코드",
	"withdraw.Chance.Currency.WithdrawFee":             "해당 화폐의 출금 수수료",
	"withdraw.Chance.Currency.IsCoin":                  "화폐의 코인 여부",
	"withdraw.Chance.Currency.WalletState":             "해당 화폐의 지갑 상태",
	"withdraw.Chance.Currency.WalletSupport":           "해당 화폐가 지원하는 입출금 정보",
	"withdraw.Chance.Account":                          "사용자의 계좌 정보",
	"withdraw.Chance.WithdrawLimit":                    "출금 제약 정보",
	"withdraw.Chance.WithdrawLimit.Currency":           "화폐를 의미하는 영문 대문자 코드",
	"withdraw.Chance.WithdrawLimit.Minimum":            "출금 최소 금액/수량",
	"withdraw.Chance.WithdrawLimit.Onetime":            "1회 출금 한도",
	"withdraw.Chance.WithdrawLimit.Daily":              "1일 출금 한도",
	"withdraw.Chance.WithdrawLimit.RemainingDaily":     "1일 잔여 출금 한도",
	"withdraw.Chance.WithdrawLimit.RemainingDailyKrw":  "통합 1일 잔여 출금 한도",
	"withdraw.Chance.WithdrawLimit.Fixed":              "출금 금액/수량 소수점 자리 수",
	"withdraw.Chance.WithdrawLimit.CanWithdraw":        "출금 지원 여부",
	"withdraw.Withdraw":                                "출금 정보",
	"withdraw.Withdraw.Type":                           "입출금 종류",
	"withdraw.Withdraw.UUID":                           "출금의 고유 아이디",
	"withdraw.Withdraw.Currency":                       "화폐를 의미하는 영문 대문자 코드",
	"withdraw.Withdraw.TxID":                           "출금의 트랜젝션 아이디",
	"withdraw.Withdraw.State":                          "출금 상태",
	"withdraw.Withdraw.CreatedAt":                      "출금 생성 시간",
	"withdraw.Withdraw.DoneAt":                         "출금 완료 시간",
	"withdraw.Withdraw.Amount":                         "출금 금액/수량",
	"withdraw.Withdraw.Fee":                            "출금 수수료",
	"withdraw.Withdraw.KrwAmount":                      "원화 환산 가격",

	// market
	"quotation.Market":             "마켓 정보",
	"quotation.Market.Makret":      "업비트에서 제공중인 시장 정보",
	"quotation.Market.KoreanName":  "거래 대상 암호화폐 한글명",
	"quotation.Market.EnglishName": "거래 대상 암호화폐 영문명",
	// candle
	"quotation.Candle":                      "시세 캔들 정보",
	"quotation.Candle.Market":               "마켓명",
	"quotation.Candle.CandleDateTimeUTC":    "캔들 기준 시각(UTC 기준)",
	"quotation.Candle.CandleDateTimeKST":    "캔들 기준 시각(KST 기준)",
	"quotation.Candle.OpeningPrice":         "시가",
	"quotation.Candle.HighPrice":            "고가",
	"quotation.Candle.LowPrice":             "저가",
	"quotation.Candle.TradePrice":           "종가",
	"quotation.Candle.TimeStamp":            "해당 캔들에서 마지막 틱이 저장된 시각",
	"quotation.Candle.CandleAccTradePrice":  "누적 거래 금액",
	"quotation.Candle.CandleAccTradeVolume": "누적 거래량",
	"quotation.Candle.Unit":                 "분단위(유닛)",
	"quotation.Candle.PrevClosingPrice":     "전일 종가(UTC 0시 기준)",
	"quotation.Candle.ChangePrice":          "전일 종가 대비 변화 금액",
	"quotation.Candle.ChangeRate":           "전일 종가 대비 변화량",
	"quotation.Candle.ConvertedTradePrice":  "종가 환산 화폐 단위로 환산된 가격",
	"quotation.Candle.FirstDayOfPeriod":     "캔들 기간의 가장 첫 날",
	// tick
	"quotation.Tick":                  "체결 정보",
	"quotation.Tick.Market":           "마켓 구분 코드",
	"quotation.Tick.TradeDateUtc":     "체결 일자(UTC)",
	"quotation.Tick.TradeTimeUtc":     "체결 시각(UTC)",
	"quotation.Tick.Timestamp":        "체결 타임스템프",
	"quotation.Tick.TradePrice":       "체결 가격",
	"quotation.Tick.TradeVolume":      "체결량",
	"quotation.Tick.PrevClosingPrice": "전일 종가",
	"quotation.Tick.ChangePrice":      "변화량",
	"quotation.Tick.AskBid":           "매도/매수",
	"quotation.Tick.SequentialID":     "체결 번호(Unique)",
	// ticker
	"quotation.Ticker":                    "시세 ticker 정보",
	"quotation.Ticker.Market":             "종목 구분 코드",
	"quotation.Ticker.TradeDate":          "최근 거래 일자(UTC)",
	"quotation.Ticker.TradeTime":          "최근 거래 시각(UTC)",
	"quotation.Ticker.TradeDateKst":       "최근 거래 일자(KST)",
	"quotation.Ticker.TradeTimeKst":       "최근 거래 시각(KST)",
	"quotation.Ticker.OpeningPrice":       "시가",
	"quotation.Ticker.HighPrice":          "고가",
	"quotation.Ticker.LowPrice":           "저가",
	"quotation.Ticker.TradePrice":         "종가",
	"quotation.Ticker.PrevClosingPrice":   "전일 종가",
	"quotation.Ticker.Change":             "EVEN : 보합, RISE : 상승, FALL : 하락",
	"quotation.Ticker.ChangePrice":        "변화액의 절대값",
	"quotation.Ticker.ChangeRate":         "변화율의 절대값",
	"quotation.Ticker.SignedChangePrice":  "부호가 있는 변화액",
	"quotation.Ticker.SignedChangeRate":   "부화가 있는 변화율",
	"quotation.Ticker.TradeVolume":        "가장 최근 거래량",
	"quotation.Ticker.AccTradePrice":      "누적 거래대금(UTC 0시 기준)",
	"quotation.Ticker.AccTradePrice24h":   "24시간 누적 거래대금",
	"quotation.Ticker.AccTradeVolume":     "누적 거래량(UTC 0시 기준)",
	"quotation.Ticker.AccTradeVolume24h":  "24시간 누적 거래량",
	"quotation.Ticker.Highest52WeekPrice": "52주 신고가",
	"quotation.Ticker.Highest52WeekDate":  "52주 신고가 달성일",
	"quotation.Ticker.Lowest52WeekPrice":  "52주 신저가",
	"quotation.Ticker.Lowest52WeekDate":   "52주 신저가 달성일",
	"quotation.Ticker.Timestamp":          "타임스탬프",
	// orderbook
	"quotation.Orderbook":                         "시세 호가 정보",
	"quotation.Orderbook.Market":                  "마켓 코드",
	"quotation.Orderbook.Timestamp":               "호가 생성 시간",
	"quotation.Orderbook.TotalAskSize":            "호가 매도 총 잔량",
	"quotation.Orderbook.TotalBidSize":            "호가 매수 총 잔량",
	"quotation.Orderbook.OrderbookUnits":          "호가",
	"quotation.Orderbook.OrderbookUnits.AskPrice": "매도호가",
	"quotation.Orderbook.OrderbookUnits.BidPrice": "매수호가",
	"quotation.Orderbook.OrderbookUnits.AskSize":  "매도 잔량",
	"quotation.Orderbook.OrderbookUnits.BidSize":  "매수 잔량",
}
