package exchange

const (
	// ORDERBY_ASC 오름차순
	ORDERBY_ASC = "asc"
	// ORDERBY_DESC 내림차순
	ORDERBY_DESC = "desc"

	// ORDER_STATE_WAIT 체결 대기
	ORDER_STATE_WAIT = "wait"
	// ORDER_STATE_DONE 전체 체결 완료
	ORDER_STATE_DONE = "done"
	// ORDER_STATE_CANCEL 주문 취소
	ORDER_STATE_CANCEL = "cancel"

	// ORDER_SIDE_BID 매수
	ORDER_SIDE_BID = "bid"
	// ORDER_SIDE_ASK 매도
	ORDER_SIDE_ASK = "ask"

	// ORDER_TYPE_LIMIT 지정가 주문
	ORDER_TYPE_LIMIT = "limit"
	// ORDER_TYPE_PRICE 시장가 주문(매수)
	ORDER_TYPE_PRICE = "price"
	// ORDER_TYPE_MARKET 시장가 주문(매도)
	ORDER_TYPE_MARKET = "market"

	// WITHDRAW_STATE_SUBMITTING 처리 중
	WITHDRAW_STATE_SUBMITTING = "submitting"
	// WITHDRAW_STATE_SUBMITTED 처리 완료
	WITHDRAW_STATE_SUBMITTED = "submitted"
	// WITHDRAW_STATE_ALMOST_ACCEPTED 출금대기중
	WITHDRAW_STATE_ALMOST_ACCEPTED = "almost_accepted"
	// WITHDRAW_STATE_REJECTED 거부
	WITHDRAW_STATE_REJECTED = "rejected"
	// WITHDRAW_STATE_ACCEPTED 승인됨
	WITHDRAW_STATE_ACCEPTED = "accepted"
	// WITHDRAW_STATE_PROCESSING 처리 중
	WITHDRAW_STATE_PROCESSING = "processing"
	// WITHDRAW_STATE_DONE 완료
	WITHDRAW_STATE_DONE = "done"
	// WITHDRAW_STATE_CANCELED 취소됨
	WITHDRAW_STATE_CANCELED = "canceled"

	// WITHDRAW_TRANSACTION_DEFAULT 일반출금
	WITHDRAW_TRANSACTION_DEFAULT = "default"
	// WITHDRAW_TRANSACTION_INTERNAL 바로출금
	WITHDRAW_TRANSACTION_INTERNAL = "internal"

	// DEPOSIT_STATE_SUBMITTING 처리 중
	DEPOSIT_STATE_SUBMITTING = "submitting"
	// DEPOSIT_STATE_SUBMITTED 처리 완료
	DEPOSIT_STATE_SUBMITTED = "submitted"
	// DEPOSIT_STATE_ALMOST_ACCEPTED 입금대기중
	DEPOSIT_STATE_ALMOST_ACCEPTED = "almost_accepted"
	// DEPOSIT_STATE_REJECTED 거절
	DEPOSIT_STATE_REJECTED = "rejected"
	// DEPOSIT_STATE_ACCEPTED 승인됨
	DEPOSIT_STATE_ACCEPTED = "accepted"
	// DEPOSIT_STATE_PROCESSING 처리 중
	DEPOSIT_STATE_PROCESSING = "processing"

	// DEPOSIT_TRANSACTION_DEFAULT 일반입금
	DEPOSIT_TRANSACTION_DEFAULT = "default"
	// DEPOSIT_TRANSACTION_INTERNAL 바로입금
	DEPOSIT_TRANSACTION_INTERNAL = "internal"
)
